name: Deploy to EC2 with GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t victor140/vichotel:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push victor140/vichotel:latest

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Determine the package manager and install Docker
            if [ -x "$(command -v apt-get)" ]; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            elif [ -x "$(command -v yum)" ]; then
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo chkconfig docker on
            else
              echo "Unsupported package manager. Please install Docker manually."
              exit 1
            fi
            # Add the user to the docker group
            sudo usermod -aG docker $USER
            # Restart the Docker service
            sudo systemctl restart docker
            # Run Docker commands with sudo
            sudo docker pull victor140/vichotel:latest
            sudo docker stop vichotel || true
            sudo docker rm vichotel || true
            sudo docker run -d -p 8080:8080 --name vichotel \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
            -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
            -e AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}" \
            -e AWS_SECRET_KEY="${{ secrets.AWS_SECRET_KEY }}" \
            -e MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}" \
            -e MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}" \
            -e FRONTEND_TESTING_URL="${{ secrets.FRONTEND_TESTING_URL }}" \
            -e AWS_FRONTEND_URL="${{ secrets.AWS_FRONTEND_URL }}" \
            -e TWILIO_SID="${{ secrets.TWILIO_SID }}" \
            -e TWILIO_AUTHTOKEN="${{ secrets.TWILIO_AUTHTOKEN }}" \
            -e TWILIO_NUMBER="${{ secrets.TWILIO_NUMBER }}" \
            victor140/vichotel:latest
